-- ATENCION: este script elimina las tablas existentes y todos sus datos.
-- Usar para crear una base nueva o reiniciar un entorno de desarrollo.

BEGIN;

DROP FUNCTION IF EXISTS public.crear_pedido_validado(bigint, numeric, text);
DROP FUNCTION IF EXISTS public.actualizar_deuda_cliente();

DROP TABLE IF EXISTS public.detalle_pedido CASCADE;
DROP TABLE IF EXISTS public.pedidos CASCADE;
DROP TABLE IF EXISTS public.productos CASCADE;
DROP TABLE IF EXISTS public.clientes CASCADE;

CREATE TABLE public.clientes (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tipo text NOT NULL DEFAULT 'persona'
    CHECK (tipo IN ('persona', 'empresa')),
  rut text NOT NULL UNIQUE,
  correo text NOT NULL UNIQUE,
  direccion text,
  telefono text,
  limite_deuda numeric(14, 2) NOT NULL DEFAULT 100000
    CHECK (limite_deuda >= 0),
  deuda_actual numeric(14, 2) NOT NULL DEFAULT 0
    CHECK (deuda_actual >= 0),
  fecha_vencimiento_deuda date,
  activo boolean NOT NULL DEFAULT true,
  nombre text,
  apellido text,
  razon_social text,
  giro text,
  nombre_contacto text,
  auth_user_id uuid UNIQUE REFERENCES auth.users(id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT clientes_nombre_segun_tipo CHECK (
    (tipo = 'persona' AND nombre IS NOT NULL AND apellido IS NOT NULL)
    OR
    (tipo = 'empresa' AND razon_social IS NOT NULL)
  )
);

CREATE TABLE public.productos (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre text NOT NULL UNIQUE,
  precio_unitario numeric(14, 2) NOT NULL
    CHECK (precio_unitario > 0),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE public.pedidos (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  fecha timestamptz NOT NULL DEFAULT now(),
  cliente_id bigint NOT NULL
    REFERENCES public.clientes(id) ON DELETE RESTRICT,
  observaciones text,
  total numeric(14, 2) NOT NULL CHECK (total > 0),
  estado text NOT NULL DEFAULT 'pendiente'
    CHECK (estado IN ('pendiente', 'pagado', 'cancelado')),
  fecha_pago timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT pedidos_fecha_pago_coherente CHECK (
    estado = 'pagado' OR fecha_pago IS NULL
  )
);

CREATE TABLE public.detalle_pedido (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pedido_id bigint NOT NULL
    REFERENCES public.pedidos(id) ON DELETE CASCADE,
  producto text NOT NULL,
  cantidad numeric(14, 3) NOT NULL CHECK (cantidad > 0),
  precio_unitario numeric(14, 2) NOT NULL CHECK (precio_unitario > 0),
  subtotal numeric(14, 2) NOT NULL CHECK (subtotal > 0),
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX idx_clientes_auth_user_id
  ON public.clientes(auth_user_id);
CREATE INDEX idx_clientes_rut
  ON public.clientes(rut);
CREATE INDEX idx_clientes_correo
  ON public.clientes(correo);
CREATE INDEX idx_pedidos_cliente_id
  ON public.pedidos(cliente_id);
CREATE INDEX idx_pedidos_fecha
  ON public.pedidos(fecha);
CREATE INDEX idx_pedidos_estado
  ON public.pedidos(estado);
CREATE INDEX idx_detalle_pedido_pedido_id
  ON public.detalle_pedido(pedido_id);

COMMIT;
