-- ============================================================
-- 007_solicitudes_credito.sql
-- Solicitudes de aumento de crédito (límite de deuda).
-- El cliente las crea; el administrador las ve en vivo (Realtime)
-- y las aprueba/rechaza. Requiere 001–006.
-- ============================================================

BEGIN;

CREATE TABLE IF NOT EXISTS public.solicitudes_credito (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cliente_id bigint NOT NULL
    REFERENCES public.clientes(id) ON DELETE CASCADE,
  limite_actual numeric(14, 2) NOT NULL DEFAULT 0,
  limite_solicitado numeric(14, 2) NOT NULL CHECK (limite_solicitado > 0),
  mensaje text,
  estado text NOT NULL DEFAULT 'pendiente'
    CHECK (estado IN ('pendiente', 'aprobada', 'rechazada')),
  created_at timestamptz NOT NULL DEFAULT now(),
  resuelta_at timestamptz
);

CREATE INDEX IF NOT EXISTS idx_solicitudes_estado
  ON public.solicitudes_credito(estado);
CREATE INDEX IF NOT EXISTS idx_solicitudes_cliente
  ON public.solicitudes_credito(cliente_id);

-- ── Permisos + RLS ──────────────────────────────────────────
ALTER TABLE public.solicitudes_credito ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.solicitudes_credito FROM anon, authenticated;
GRANT SELECT, INSERT, UPDATE ON public.solicitudes_credito TO authenticated;

-- El cliente crea y ve sus propias solicitudes; el admin ve todas.
DROP POLICY IF EXISTS solicitudes_insert_propio ON public.solicitudes_credito;
CREATE POLICY solicitudes_insert_propio
ON public.solicitudes_credito FOR INSERT TO authenticated
WITH CHECK (public.es_mi_cliente(cliente_id) OR public.es_admin());

DROP POLICY IF EXISTS solicitudes_select ON public.solicitudes_credito;
CREATE POLICY solicitudes_select
ON public.solicitudes_credito FOR SELECT TO authenticated
USING (public.es_mi_cliente(cliente_id) OR public.es_admin());

-- Resolver (aprobar/rechazar): solo admin.
DROP POLICY IF EXISTS solicitudes_update_admin ON public.solicitudes_credito;
CREATE POLICY solicitudes_update_admin
ON public.solicitudes_credito FOR UPDATE TO authenticated
USING (public.es_admin()) WITH CHECK (public.es_admin());

-- ── RPC: resolver una solicitud (atómico, solo admin) ───────
CREATE OR REPLACE FUNCTION public.resolver_solicitud_credito(
  p_id bigint,
  p_aprobar boolean
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_sol public.solicitudes_credito%ROWTYPE;
BEGIN
  IF NOT public.es_admin() THEN
    RAISE EXCEPTION 'Solo un administrador puede resolver solicitudes.';
  END IF;

  SELECT * INTO v_sol FROM public.solicitudes_credito WHERE id = p_id;
  IF NOT FOUND THEN
    RETURN jsonb_build_object('ok', false, 'motivo', 'Solicitud no encontrada.');
  END IF;
  IF v_sol.estado <> 'pendiente' THEN
    RETURN jsonb_build_object('ok', false, 'motivo', 'La solicitud ya fue resuelta.');
  END IF;

  IF p_aprobar THEN
    UPDATE public.clientes
      SET limite_deuda = v_sol.limite_solicitado
      WHERE id = v_sol.cliente_id;
    UPDATE public.solicitudes_credito
      SET estado = 'aprobada', resuelta_at = now()
      WHERE id = p_id;
  ELSE
    UPDATE public.solicitudes_credito
      SET estado = 'rechazada', resuelta_at = now()
      WHERE id = p_id;
  END IF;

  RETURN jsonb_build_object(
    'ok', true,
    'estado', CASE WHEN p_aprobar THEN 'aprobada' ELSE 'rechazada' END
  );
END;
$$;

GRANT EXECUTE ON FUNCTION public.resolver_solicitud_credito(bigint, boolean)
  TO authenticated;

GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO authenticated;

-- ── Realtime: notificación en vivo al administrador ─────────
DO $$
BEGIN
  ALTER PUBLICATION supabase_realtime ADD TABLE public.solicitudes_credito;
EXCEPTION
  WHEN duplicate_object THEN NULL;   -- ya estaba en la publicación
  WHEN undefined_object THEN NULL;   -- la publicación no existe en este entorno
END $$;

COMMIT;
